apiVersion: v1
kind: LimitRange
metadata:
        name: limit
        namespace: onepiece
spec:
        limits:
        - default:
                memory: 512Mi
                cpu: 800m
          defaultRequest:
                memory: 256Mi
                cpu: 0.5
          max:  
                memory: 512Mi
                cpu: 800m
          min:
                memory: 100Mi
                cpu: 200m    
          type: Container
                
