apiVersion: v1
kind: Pod
metadata:
        name: hum
        namespace: naruto
spec:
        containers:
               - name: kaido
                 image: nginx
                 resources:
                   requests:
                           memory: "128Mi"

